### ISSUE TITLE
Default Drive not Selected on macOS Plotting Screen

### ISSUE THREAD

**Issue by ImmaZoni** [subspace/desktop-farmer#15]
## Error Code
 
```
See Screenshot. 
```

## Description

When on the plotting screen, when a user goes to try and select allocated space they are shown as -1GB available. If the user uses the file explorer to select a location such as Documents the information will then be correctly shown. 

*see screenshot below*
## Expected Behavior

When arriving at the plotting screen, the default home drive should be auto-selected as the drive to populate sizing and everything. 
![Screen Shot 2021-09-23 at 12 07 19 PM](https://user-images.githubusercontent.com/31865152/134569180-92436b7f-29ab-4bab-ab4c-c00bc1155076.png)

## Actual Behavior

The plotting screen shows incorrect information. 
![Screen Shot 2021-09-23 at 12 06 26 PM](https://user-images.githubusercontent.com/31865152/134569221-7955f99f-9960-47a8-b655-273f2fba86b8.png)

## Attempted Troubleshooting

Verified the bug is not correlated to code-signing for macOS (this issue is present in prior versions as well)
## Possible Fix

Set the default drive to be the home drive in macOS when opening the application, plotting should be assumed to be home drive. 

or 

We may have to just create the default directory that is already listed there.

## Context

Hard stop on a smooth user workflow, not something users will want to deal with. 
## Steps to Reproduce

1. Run any version of subspace desktop farmer < v0.0.3

## Your Environment

* Version used: v0.0.2 & v0.0.3 pre-release
* Operating System and version: macOS Catalina 10.15.7
* Desktop, Laptop, or Server: Laptop - Macbook Air

**Comment by jdheeter** [comment]
Something that would help debugging this would be to see any errors in the console. There is two ways to see the dev console.
1) follow instructions to run the app in dev mode in readme.md, basically run `yarn quasar dev` (wait for it to finish) in one terminal and then `yarn tauri dev` in another terminal. Then you can right click the app windows and click inspect > console
2) You can build a dev version, this is more like the final release executable except it has logging enabled. To build the dev version just run `yarn build:debug` and read the logs to see where the final build files are now located. In the debug version you can right click in the window and hit inspect to see the console.

There should be an error in the console that would help us pinpoint why the UI isn't populating correctly. One thought I have is because the default directory doesn't exist yet and it's not properly handling that situation.

**Comment by ImmaZoni** [comment]
Issue resolved with latest updates.
